### PR TITLE
Python3 Compatibility

### PR DESCRIPTION
**Pull request by ghost**
Really well-coded! It only required some small changes to a UTF-8ifying function.

I added Python3 to the metadata and bumped the minor version. The test cases fail, but they are the same failures as with Python2, and at least one of them is seemingly testing for failure, and the other is the API returning an unexpected string. That's when a different username for geonames is provided, of course.

Nice wrapper, thanks. :)

### CODE REVIEW

**Comment by jayvdb** [comment]
:-1: 

After #5, all tests pass on Python 2.

To run the tests on your machine, you need to run the tests like

``` bash
GEOGOTCHI_USERNAME=xxxx py.test tests.py
```

**Comment by ghost** [comment]
Here's the test output I get on Py3, and in both cases the error appears to lie in changed server-provided data or server-returned errors since the TCs were written:

```
========================================== test session starts ==========================================
platform linux -- Python 3.5.2, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/cathal/Projects/python/geogotchi, inifile: 
collected 13 items 

tests.py .......F..F..

=============================================== FAILURES ================================================
_________________________________ TestGeogotchi.test_get_hierarchy_bad __________________________________

self = <tests.TestGeogotchi testMethod=test_get_hierarchy_bad>

    def test_get_hierarchy_bad(self):
        bad_geoname = 1234123412341234
>       self.assertRaises(errors.OtherError, gg.get_hierarchy, bad_geoname)

tests.py:117: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
geogotchi/base.py:216: in get_hierarchy
    parsed_response = self._parse_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def _parse_response(self, response):
        """Parse response. Returns a Python structure or raises an exception.
            """
        status_code = response.status_code
        if status_code != 200:
>           raise errors.GeogotchiError("status code: %s" % status_code)
E           geogotchi.errors.GeogotchiError: status code: 503

geogotchi/base.py:184: GeogotchiError
____________________________________ TestGeogotchi.test_search_basic ____________________________________

self = <tests.TestGeogotchi testMethod=test_search_basic>

    def test_search_basic(self):
        name = itemgetter("name")
        def check_name(cmp_name, **kwargs):
            self.assertEqual(cmp_name,
                             name(gg.search(max_rows=1, **kwargs)[0]))

        check_name(u"Sweden", q="Sweden")
        check_name(u"Sverige", q="Sweden", lang="sv")
>       check_name(u"Arlanda", name="Arlanda", feature_code="AIRP")

tests.py:127: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests.py:123: in check_name
    name(gg.search(max_rows=1, **kwargs)[0]))
E   AssertionError: 'Arlanda' != 'Stockholm-Arlanda Airport'
E   - Arlanda
E   + Stockholm-Arlanda Airport
================================== 2 failed, 11 passed in 2.03 seconds ==================================
```

**Comment by ghost** [comment]
When I ran the tests on 2 or 3 I got the same outcomes, though at that time I was not using pytest, I was simply running tests.py with the built-in unittests module:

``` bash
$ python2 -m unittest tests
.......E..F..
======================================================================
ERROR: test_get_hierarchy_bad (tests.TestGeogotchi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 117, in test_get_hierarchy_bad
    self.assertRaises(errors.OtherError, gg.get_hierarchy, bad_geoname)
  File "/usr/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "geogotchi/base.py", line 216, in get_hierarchy
    parsed_response = self._parse_response(response)
  File "geogotchi/base.py", line 184, in _parse_response
    raise errors.GeogotchiError("status code: %s" % status_code)
GeogotchiError: status code: 503

======================================================================
FAIL: test_search_basic (tests.TestGeogotchi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 127, in test_search_basic
    check_name(u"Arlanda", name="Arlanda", feature_code="AIRP")
  File "tests.py", line 123, in check_name
    name(gg.search(max_rows=1, **kwargs)[0]))
AssertionError: u'Arlanda' != u'Stockholm-Arlanda Airport'
- Arlanda
+ Stockholm-Arlanda Airport


----------------------------------------------------------------------
Ran 13 tests in 1.532s

FAILED (failures=1, errors=1)
```

**Comment by ghost** [comment]
vs. for Python3:

``` bash
$ python3 -m unittest tests
.......E..F..
======================================================================
ERROR: test_get_hierarchy_bad (tests.TestGeogotchi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cathal/Projects/python/geogotchi/tests.py", line 117, in test_get_hierarchy_bad
    self.assertRaises(errors.OtherError, gg.get_hierarchy, bad_geoname)
  File "/usr/lib/python3.5/unittest/case.py", line 727, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/python3.5/unittest/case.py", line 176, in handle
    callable_obj(*args, **kwargs)
  File "/home/cathal/Projects/python/geogotchi/geogotchi/base.py", line 216, in get_hierarchy
    parsed_response = self._parse_response(response)
  File "/home/cathal/Projects/python/geogotchi/geogotchi/base.py", line 184, in _parse_response
    raise errors.GeogotchiError("status code: %s" % status_code)
geogotchi.errors.GeogotchiError: status code: 503

======================================================================
FAIL: test_search_basic (tests.TestGeogotchi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cathal/Projects/python/geogotchi/tests.py", line 127, in test_search_basic
    check_name(u"Arlanda", name="Arlanda", feature_code="AIRP")
  File "/home/cathal/Projects/python/geogotchi/tests.py", line 123, in check_name
    name(gg.search(max_rows=1, **kwargs)[0]))
AssertionError: 'Arlanda' != 'Stockholm-Arlanda Airport'
- Arlanda
+ Stockholm-Arlanda Airport


----------------------------------------------------------------------
Ran 13 tests in 3.500s

FAILED (failures=1, errors=1)
```

So.. appears unrelated to my PR adding Python3 support. Even the errors are consistent between versions! :trophy:

**Comment by jayvdb** [comment]
After #5 , you can add Travis testing on Python 3.

**Comment by ghost** [comment]
Ah, it wasn't clear to me that you were talking about another unmerged PR; thought you were suggesting the PR be rejected because tests were passing upstream. Sorry for the confusion.

Yes; the test cases need updating, and the trivial changes needed to support Py3 (included here) mean that this lib could be up-to-date and modernised pretty soon. I'm actually looking forward to playing with it for pet geo-projects too, not just for work (which is how I found it).

**Comment by ghost** [comment]
I'm starting to think we may have to make a fork, @jayvdb :)

**Pull request closed without merging**
